<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { request } from '../api'
import { ensureArray, formatDate, formatMoney } from '../utils'
import { useToast } from '../composables/useToast'

const route=useRoute(),router=useRouter(),toast=useToast(),loading=ref(true),detail=ref(null)
const type=computed(()=>String(route.params.type)),isBuy=computed(()=>type.value==='buy_demand'),entity=computed(()=>detail.value?.entity||{}),sources=computed(()=>(detail.value?.sources||[]).map(x=>({...x,uploadedText:formatDate(x.uploaded_at),relationText:({initial:'首次录入',duplicate_source:'重复来源',supplement:'补充信息'})[x.relation_type]||x.relation_type})))
const events=computed(()=>(detail.value?.merge_events||[]).map(x=>({...x,createdText:formatDate(x.created_at),actionText:x.action==='split'?'撤销合并':x.merge_method==='canonical_hash'?'完全重复关联':x.merge_method==='structured_supplement'?'补充信息合并':'语义合并',canRevert:x.action==='merge'&&!x.reverted_at&&x.reason?.target_before})))

function valueText(v){if(v===null||v===undefined||v==='')return'';if(Array.isArray(v))return v.filter(Boolean).join('、');if(typeof v==='object')return Object.values(v).map(valueText).filter(Boolean).join('；');return String(v)}
function moneyRange(min,max){if(min==null)return max==null?'':`不超过 ${formatMoney(max)}`;if(max==null)return`不少于 ${formatMoney(min)}`;return Number(min)===Number(max)?formatMoney(min):`${formatMoney(min)} 至 ${formatMoney(max)}`}
function numberRange(min,max){if(min==null)return max==null?'':`不超过 ${max}`;if(max==null)return`不少于 ${min}`;return Number(min)===Number(max)?String(min):`${min} 至 ${max}`}
function percent(v){if(v==null)return'';const n=Number(v);return`${n<=1?n*100:n}%`}
function percentRange(min,max){const l=percent(min),r=percent(max);if(!l)return r?`不超过 ${r}`:'';if(!r)return`不少于 ${l}`;return l===r?l:`${l} 至 ${r}`}
const points=computed(()=>{const e=entity.value,result=[];const add=(label,value)=>{const text=valueText(value);if(text)result.push({label,value:text,key:`${label}-${result.length}`})};add('行业',e.industries);add('交易方式',e.transaction_types);if(isBuy.value){add('标的类型',e.target_types);add('投资阶段',e.preferred_stages);add('偏好地区',e.preferred_regions);add('投资金额',moneyRange(e.investment_amount_min,e.investment_amount_max));add('目标营收',moneyRange(e.target_revenue_min,e.target_revenue_max));add('目标净利润',moneyRange(e.target_net_profit_min,e.target_net_profit_max));add('目标估值',moneyRange(e.target_valuation_min,e.target_valuation_max));add('PE 要求',numberRange(e.pe_min,e.pe_max));add('上市要求',e.listed_status_requirement);add('最低控股比例',percent(e.control_ratio_min));if(e.profitability_required!=null)add('盈利要求',e.profitability_required?'要求盈利':'不限是否盈利');addExtras(result,e.extra_constraints,'其他条件')}else{add('项目类型',e.project_types);add('融资轮次',e.financing_round);add('融资金额',moneyRange(e.financing_amount_min,e.financing_amount_max));add('营收',moneyRange(e.revenue_min,e.revenue_max));add('净利润',moneyRange(e.net_profit_min,e.net_profit_max));add('估值',moneyRange(e.valuation_min,e.valuation_max));add('PE',numberRange(e.pe_min,e.pe_max));add('所在地区',[e.province,e.city].filter(Boolean));add('上市状态',e.listed_status);add('可转让比例',percentRange(e.transfer_ratio_min,e.transfer_ratio_max));addExtras(result,e.extra_facts,'其他信息')}return result})
function addExtras(result,extra,prefix){if(!extra||typeof extra!=='object'||Array.isArray(extra))return;const labels={exclude:'排除项',preferred_location:'偏好地点',preferred_themes:'偏好主题',status:'状态',requirements:'要求',highlights:'亮点'};Object.keys(extra).forEach(key=>{if(key.startsWith('local_')||key.startsWith('sub_'))return;const value=valueText(extra[key]);if(value)result.push({key:`${prefix}-${key}`,label:`${prefix} · ${labels[key]||key}`,value})})}
function level(score){const v=Number(score||0);return v>=.8?['worth_following','值得跟进']:v>=.65?['recommended','建议了解']:['possibly_relevant','可能相关']}
function rows(signals,status){const map={matched:['✓ 匹配','yes'],conflict:['✕ 不匹配','no'],missing:['? 待补充','missing']};return ensureArray(signals).map((x,index)=>{const b=x.buyer_value||'',s=x.seller_value||'';if(!b&&!s)return null;return{key:`${x.field||status}-${index}`,label:x.label||x.message||'其他条件',primary:isBuy.value?(b||'未披露'):(s||'未披露'),counterpart:isBuy.value?(s||'未披露'):(b||'未披露'),statusText:map[status][0],statusClass:map[status][1]}}).filter(Boolean)}
const matches=computed(()=>(detail.value?.matches||[]).map(item=>{const lv=level(item.final_score);return{...item,scoreText:Math.round(Number(item.final_score||0)*100),levelClass:item.level||lv[0],levelText:item.level_text||lv[1],rows:[...rows(item.matched,'matched'),...rows(item.conflicts,'conflict'),...rows(item.missing,'missing')]}}))
async function load(){loading.value=true;try{detail.value=await request(`/entities/${type.value}/${route.params.id}`)}catch(error){toast.show(error.message)}finally{loading.value=false}}
async function revert(id){if(!confirm('来源信息将拆回原实体，并恢复合并前版本。是否继续？'))return;try{await request(`/merge-events/${id}/revert`,{method:'POST'});toast.show('已撤销合并');load()}catch(error){toast.show(error.message)}}
onMounted(load);watch(()=>route.fullPath,load)
</script>

<template><div class="page no-tabs detail-page" :class="isBuy?'buy-theme':'sell-theme'"><header class="page-head"><button @click="router.back()">‹</button><h1>{{isBuy?'投资需求详情':'项目需求详情'}}</h1><span></span></header><div v-if="loading" class="loading"><t-loading theme="circular" /> 加载中…</div><template v-else-if="detail"><section class="panel"><h2 class="entity-title">{{entity.title}}</h2><div v-if="entity.buyer_name||entity.company_name" class="entity-sub">{{entity.buyer_name||entity.company_name}}</div><p class="summary">{{entity.summary||'暂无摘要'}}</p><h3 class="point-heading">{{isBuy?'投资要点':'项目要点'}}（{{points.length}}）</h3><div class="point-list"><div v-for="p in points" :key="p.key" class="data-point"><span>{{p.label}}</span><b>{{p.value}}</b></div></div></section>
<h2 class="section-title">匹配结果</h2><article v-for="match in matches" :key="match.entity_id" class="panel match-card"><div class="match-head"><div><h3>{{match.title}}</h3><span class="level" :class="match.levelClass">{{match.levelText}}</span></div><div class="score"><b>{{match.scoreText}}</b>分</div></div><div class="table"><div class="tr th"><b>对比内容</b><b>{{isBuy?'投资方':'项目方'}}</b><b>{{isBuy?'项目方':'投资方'}}</b><b>是否匹配</b></div><div v-for="row in match.rows" :key="row.key" class="tr"><b>{{row.label}}</b><span>{{row.primary}}</span><span>{{row.counterpart}}</span><strong :class="row.statusClass">{{row.statusText}}</strong></div><div v-if="!match.rows.length" class="table-empty">暂无双方已披露的可对比信息</div></div><button class="match-more" @click="router.push(`/entities/${match.entity_type}/${match.entity_id}`)">查看完整资料 ›</button></article><div v-if="!matches.length" class="empty">暂无匹配结果</div>
<h2 v-if="events.length" class="section-title">合并记录</h2><article v-for="event in events" :key="event.id" class="panel event"><div><b>{{event.actionText}}</b><span>{{event.createdText}}</span></div><p v-if="event.operator">操作人：{{event.operator}}</p><button v-if="event.canRevert" class="danger-btn" @click="revert(event.id)">撤销本次合并</button></article>
<h2 class="section-title">原始信息来源（{{sources.length}}）</h2><article v-for="source in sources" :key="source.id" class="panel source"><div><b>{{source.uploader||'历史数据'}}</b><span class="relation">{{source.relationText}}</span></div><time>{{source.uploadedText}}</time><p>{{source.raw_text}}</p></article></template></div></template>

<style scoped>
.detail-page{--theme:#0052d9;--theme-soft:#eef4ff}.detail-page.sell-theme{--theme:#00a870;--theme-soft:#e8f8f2}.page-head{display:grid;grid-template-columns:40px 1fr 40px;align-items:center;margin-bottom:18px}.page-head button{border:0;background:none;color:#334155;font-size:32px}.page-head h1{margin:0;color:var(--theme);text-align:center;font-size:20px}.entity-title{margin:0;color:#172033;font-size:23px;line-height:1.4}.entity-sub{margin-top:6px;color:#64748b}.summary{margin:14px 0 0;color:#475569;font-size:15px;line-height:1.7}.point-heading{margin:17px 0 0;padding-top:15px;border-top:1px solid #eef2f7;color:var(--theme);font-size:15px}.point-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:11px}.data-point{display:flex;min-width:0;flex-direction:column;gap:6px;padding:11px;border:1px solid var(--theme-soft);border-radius:9px;background:var(--theme-soft)}.data-point span{color:#94a3b8;font-size:12px}.data-point b{color:#334155;font-size:14px;line-height:1.45;overflow-wrap:anywhere}.match-head{display:flex;justify-content:space-between;gap:12px}.match-head h3{margin:0;color:#172033;font-size:17px}.level{display:inline-block;margin-top:8px;padding:4px 9px;border-radius:999px;background:#eef2f7;color:#64748b;font-size:12px}.level.worth_following{background:#e8f8f2;color:#008858}.level.recommended{background:#fff4df;color:#b86b00}.score{flex:none;color:var(--theme);font-size:12px}.score b{font-size:28px}.table{overflow:hidden;margin-top:17px;border:1px solid #e5eaf0;border-radius:9px}.tr{display:grid;grid-template-columns:20% 27% 27% 26%;border-bottom:1px solid #e8edf3}.tr:last-child{border-bottom:0}.tr>*{display:flex;min-width:0;align-items:center;padding:10px 5px;border-right:1px solid #e8edf3;color:#475569;font-size:12px;line-height:1.45;overflow-wrap:anywhere}.tr>*:last-child{justify-content:center;border-right:0;text-align:center}.tr>b{color:#334155}.th{background:#f7f9fc}.th>*{color:#64748b!important;font-weight:600}.yes{color:#087f5b!important}.no{color:#c2413a!important}.missing{color:#8a6d1d!important}.table-empty{padding:24px;color:#94a3b8;text-align:center;font-size:13px}.match-more{display:block;margin:13px 0 0 auto;border:0;background:none;color:var(--theme);font-size:13px}.event>div,.source>div{display:flex;justify-content:space-between;gap:12px}.event span,.source time{color:#94a3b8;font-size:12px}.event p{color:#64748b;font-size:13px}.relation{padding:3px 8px;border-radius:999px;background:var(--theme-soft);color:var(--theme)!important}.source time{display:block;margin-top:6px}.source p{margin:13px 0 0;color:#475569;font-size:14px;line-height:1.7;white-space:pre-wrap}
</style>
